### ISSUE TITLE
Pilot scorecards GitHub Action

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/agent#35]

**Comment by varunsh-coder** [comment]
- [ ] Signed-Releases - valid finding - will create an issue for this
- [ ] Code-Review - valid finding
- [ ] Branch Protection - false positive. This repo has branch protection for default branch. Error from Scorecard: _internal error: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by integration_. It should not create an alert on error. 
- [ ] Token-Permissions - raised high severity issue since top level permissions are missing. 
- [ ] Dependency-Update-Tool - false positive. I do have dependabot enabled, though for some reason, dependabot has not created a PR as of now.
- [ ] Security-Policy - valid finding though Scorecards got an error: _repo unreachable: GET https://api.github.com/repos/step-security/.github: 404 Not Found []_
- [ ] SAST Tool - SAST tool detected but not run on all commmits - I think requirement to run it on all commits may be too high. CodeQL takes time to run. Running on PR to main and running once a week should be ok IMHO. 
- [ ] Packaging - false positive - Not applicable as of now. 
- [ ] Fuzzing - valid finding
- [ ] Pinned Dependency - valid finding 
- [ ] Contributors - valid finding
- [ ] CII badge - valid finding

**Comment by varunsh-coder** [comment]
Completed pilot

**Comment by laurentsimon** [comment]
> * [x]  Signed-Releases - valid finding - created [Sign agent release #37](https://github.com/step-security/agent/issues/37)
> * [x]  Code-Review - valid finding
> * [x]  Branch Protection - false positive. This repo has branch protection for default branch. Error from Scorecard: _internal error: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by integration_. It should not create an alert on error.

We've seen this before https://github.com/ossf/scorecard/issues/1097 and we're not sure why it's happening. How often does it happen?

> * [x]  Token-Permissions - raised high severity issue since top level permissions are missing. Will address via secure-workflows
> * [x]  Dependency-Update-Tool - false positive. I do have dependabot enabled, though for some reason, dependabot has not created a PR as of now.

We currently only check for the dependabot config file being present. How would you like us to change this behavior?

> * [x]  Security-Policy - valid finding though Scorecards got an error: _repo unreachable: GET https://api.github.com/repos/step-security/.github: 404 Not Found []_. Created [Add security policy to repo #38](https://github.com/step-security/agent/issues/38) to address

The NotFound was fixed recently in https://github.com/ossf/scorecard/pull/1277, but is not used in the action code you used yet.

> * [x]  SAST Tool - SAST tool detected but not run on all commmits - I think requirement to run it on all commits may be too high. CodeQL takes time to run. Running on PR to main and running once a week should be ok IMHO. Created [Configure CodeQL to run on PR #39](https://github.com/step-security/agent/issues/39) to adjust CodeQL runs.

we have a relevant tracking issue on this https://github.com/ossf/scorecard/issues/1268. Feel free to chime in.

> * [x]  Packaging - false positive - Not applicable as of now.

this check is unreliable, agreed.

> * [x]  Fuzzing - valid finding. created [Add fuzzing tool #41](https://github.com/step-security/agent/issues/41)
> * [x]  Pinned Dependency - valid finding. created [Pin dependencies in action workflows #40](https://github.com/step-security/agent/issues/40). Will also add feature to secure-workflows.
> * [x]  Contributors - valid finding
> * [x]  CII badge - valid finding - created [Add CII badge #42](https://github.com/step-security/agent/issues/42)

Thanks for the feedback!

**Comment by evverx** [comment]
>  I do have dependabot enabled, though for some reason, dependabot has not created a PR as of now.

As far as I know there are two types of Dependabot. One of them is configured with `.github/dependabot.yml` and the other one is responsible for security updates: https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates. My guess would be that the "security" dependabot is enabled for this repository. I'm not sure how to figure out whether it's enabled using GitHub API though

**Comment by varunsh-coder** [comment]
> > I do have dependabot enabled, though for some reason, dependabot has not created a PR as of now.
> 
> As far as I know there are two types of Dependabot. One of them is configured with `.github/dependabot.yml` and the other one is responsible for security updates: https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates. My guess would be that the "security" dependabot is enabled for this repository. I'm not sure how to figure out whether it's enabled using GitHub API though

Yes, that is right - the "security" dependabot is enabled for this repo. I did actually get a PR from dependabot today. One way to figure out if dependabot is enabled could be to check the last X PRs to see if one is from dependabot. I have seen similar other checks in Scorecards. While not perfect, if dependabot is enabled, there is high likelihood that it would have created some PRs...

**Comment by varunsh-coder** [comment]
> > * [x]   Signed-Releases - valid finding - created [Sign agent release #37](https://github.com/step-security/agent/issues/37)
> > * [x]   Code-Review - valid finding
> > * [x]   Branch Protection - false positive. This repo has branch protection for default branch. Error from Scorecard: _internal error: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by integration_. It should not create an alert on error.
> 
> We've seen this before [ossf/scorecard#1097](https://github.com/ossf/scorecard/issues/1097) and we're not sure why it's happening. How often does it happen?

Its happened every time the Scorecards GitHub action has run today on this repo - 5 odd times. 

> 
> > * [x]   Token-Permissions - raised high severity issue since top level permissions are missing. Will address via secure-workflows
> > * [x]   Dependency-Update-Tool - false positive. I do have dependabot enabled, though for some reason, dependabot has not created a PR as of now.
> 
> We currently only check for the dependabot config file being present. How would you like us to change this behavior?

One way to figure out if dependabot is enabled could be to check the last X PRs to see if one is from dependabot. I have seen similar other checks in Scorecards. While not perfect, if dependabot is enabled, there is high likelihood that it would have created some PRs...

> 
> > * [x]   Security-Policy - valid finding though Scorecards got an error: _repo unreachable: GET https://api.github.com/repos/step-security/.github: 404 Not Found []_. Created [Add security policy to repo #38](https://github.com/step-security/agent/issues/38) to address
> 
> The NotFound was fixed recently in [ossf/scorecard#1277](https://github.com/ossf/scorecard/pull/1277), but is not used in the action code you used yet.
> 
> > * [x]   SAST Tool - SAST tool detected but not run on all commmits - I think requirement to run it on all commits may be too high. CodeQL takes time to run. Running on PR to main and running once a week should be ok IMHO. Created [Configure CodeQL to run on PR #39](https://github.com/step-security/agent/issues/39) to adjust CodeQL runs.
> 
> we have a relevant tracking issue on this [ossf/scorecard#1268](https://github.com/ossf/scorecard/issues/1268). Feel free to chime in.
> 
> > * [x]   Packaging - false positive - Not applicable as of now.
> 
> this check is unreliable, agreed.
> 
> > * [x]   Fuzzing - valid finding. created [Add fuzzing tool #41](https://github.com/step-security/agent/issues/41)
> > * [x]   Pinned Dependency - valid finding. created [Pin dependencies in action workflows #40](https://github.com/step-security/agent/issues/40). Will also add feature to secure-workflows.
> > * [x]   Contributors - valid finding
> > * [x]   CII badge - valid finding - created [Add CII badge #42](https://github.com/step-security/agent/issues/42)
> 
> Thanks for the feedback!

**Comment by varunsh-coder** [comment]
Hi @laurentsimon yesterday when I added the `harden-runner` GitHub Action to the workflow for piloting scorecards, I observed calls to bestpractices.coreinfrastructure.org and api.osv.dev. Are these expected? I can imagine call to api.osv.dev may be storing the results, but not sure what bestpractices.coreinfrastructure.org is for. You can see the insights [here](https://app.stepsecurity.io/github/step-security/agent/actions/runs/1496999022). Also, would be great if you can tell me if this insights UI looks intuitive or ideas to make it better. 

I had also added `contents:read` permission to the workflow with the hope that the call to get branch protection info to GitHub API would succeed, but it did not. 

Also, while I pinned all GitHub actions to their commit SHAs ([secure-workflows](https://app.stepsecurity.io/secureworkflow) supports this now), I am still getting this issue flagged when one of the [actions](https://github.com/step-security/agent/blob/1ba7efeb825f5cce56a1b8851971d569a662a96b/.github/workflows/int.yml#L44) is using docker://. I believe this is a false positive. Can you please confirm? Thanks!

**Comment by laurentsimon** [comment]
> Hi @laurentsimon yesterday when I added the `harden-runner` GitHub Action to the workflow for piloting scorecards, I observed calls to bestpractices.coreinfrastructure.org and api.osv.dev. Are these expected? 

yes, those are expected. `bestpractices.coreinfrastructure.org` is or the CII check, `api.osv.dev` for the `Vulnerabilities` check.

You can see the insights [here](https://app.stepsecurity.io/github/step-security/agent/actions/runs/1496999022). Request you to please review the KB for this action [here](https://github.com/step-security/secure-workflows/blob/0dc63678d826e330792fc0790898d039fa0fa7b9/knowledge-base/ossf/scorecard-actions/analyze/action-security.yml). Please let me know what permissions it needs and the reasons for calling these endpoints.

`read-all` should be enough. 

> Also, while I pinned all GitHub actions to their commit SHAs, I am still getting this issue flagged when one of the [actions](https://github.com/step-security/agent/blob/1ba7efeb825f5cce56a1b8851971d569a662a96b/.github/workflows/int.yml#L44) is using docker://. I believe this is a false positive. Can you please confirm? Thanks!

I think this is intended because you have not pinned by hash, only by `latest` which is mutable.

**Comment by varunsh-coder** [comment]
> > Hi @laurentsimon yesterday when I added the `harden-runner` GitHub Action to the workflow for piloting scorecards, I observed calls to bestpractices.coreinfrastructure.org and api.osv.dev. Are these expected?
> 
> yes, those are expected. `bestpractices.coreinfrastructure.org` is or the CII check, `api.osv.dev` for the `Vulnerabilities` check.

Thanks! I added the info to the KB. 

> 
> You can see the insights [here](https://app.stepsecurity.io/github/step-security/agent/actions/runs/1496999022). Request you to please review the KB for this action [here](https://github.com/step-security/secure-workflows/blob/0dc63678d826e330792fc0790898d039fa0fa7b9/knowledge-base/ossf/scorecard-actions/analyze/action-security.yml). Please let me know what permissions it needs and the reasons for calling these endpoints.
> 
> `read-all` should be enough.

I tried to set it to `read-all`, but if there is another Action in the workflow that needs a `write`, then I could not get it to work. `permissions` can either be a string or a map of strings, but with `read-all` and `security-events:write`, it needed to be both string and a map, which was not working...Let me know if I am missing something. For the time being, I reviewed the code and have set the explicit read permissions. Feel free to review [here](https://github.com/step-security/secure-workflows/blob/main/knowledge-base/ossf/scorecard-actions/analyze/action-security.yml). 

> 
> > Also, while I pinned all GitHub actions to their commit SHAs, I am still getting this issue flagged when one of the [actions](https://github.com/step-security/agent/blob/1ba7efeb825f5cce56a1b8851971d569a662a96b/.github/workflows/int.yml#L44) is using docker://. I believe this is a false positive. Can you please confirm? Thanks!
> 
> I think this is intended because you have not pinned by hash, only by `latest` which is mutable.

Got it. My bad. Will fix it...

**Comment by laurentsimon** [comment]
> > > Hi @laurentsimon yesterday when I added the `harden-runner` GitHub Action to the workflow for piloting scorecards, I observed calls to bestpractices.coreinfrastructure.org and api.osv.dev. Are these expected?
> > 
> > 
> > yes, those are expected. `bestpractices.coreinfrastructure.org` is or the CII check, `api.osv.dev` for the `Vulnerabilities` check.
> 
> Thanks! I added the info to the KB.
> 
> > You can see the insights [here](https://app.stepsecurity.io/github/step-security/agent/actions/runs/1496999022). Request you to please review the KB for this action [here](https://github.com/step-security/secure-workflows/blob/0dc63678d826e330792fc0790898d039fa0fa7b9/knowledge-base/ossf/scorecard-actions/analyze/action-security.yml). Please let me know what permissions it needs and the reasons for calling these endpoints.
> > `read-all` should be enough.
> 
> I tried to set it to `read-all`, but if there is another Action in the workflow that needs a `write`, then I could not get it to work. `permissions` can either be a string or a map of strings, but with `read-all` and `security-events:write`, it needed to be both string and a map, which was not working...

my bad: you're right. `security-events:write` is needed to upload the results to the GitHub scanning dashboard

Let me know if I am missing something. For the time being, I reviewed the code and have set the explicit read permissions. Feel free to review [here](https://github.com/step-security/secure-workflows/blob/main/knowledge-base/ossf/scorecard-actions/analyze/action-security.yml).
> 
> > > Also, while I pinned all GitHub actions to their commit SHAs, I am still getting this issue flagged when one of the [actions](https://github.com/step-security/agent/blob/1ba7efeb825f5cce56a1b8851971d569a662a96b/.github/workflows/int.yml#L44) is using docker://. I believe this is a false positive. Can you please confirm? Thanks!
> > 
> > 
> > I think this is intended because you have not pinned by hash, only by `latest` which is mutable.
> 
> Got it. My bad. Will fix it...
